# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mondaycom',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/mondaycom',
                'lib_path': 'src/mondaycom'},
  'syms': { 'mondaycom.core': { 'mondaycom.core.create_md_tasklist': ('core.html#create_md_tasklist', 'mondaycom/core.py'),
                                'mondaycom.core.get_data': ('core.html#get_data', 'mondaycom/core.py'),
                                'mondaycom.core.get_items': ('core.html#get_items', 'mondaycom/core.py'),
                                'mondaycom.core.get_start_date': ('core.html#get_start_date', 'mondaycom/core.py'),
                                'mondaycom.core.item_to_markdown': ('core.html#item_to_markdown', 'mondaycom/core.py'),
                                'mondaycom.core.query_sprint_tasks': ('core.html#query_sprint_tasks', 'mondaycom/core.py')}}}
