"""Functions to make the use of Monday.com even easier for Jelle."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['apiKey', 'apiUrl', 'headers', 'query_board_columns', 'query_sprint_tasks', 'get_data', 'get_start_date', 'get_items',
           'item_to_markdown', 'create_md_tasklist']

# %% ../../nbs/00_core.ipynb 3
import requests
import os
from dotenv import load_dotenv
from textwrap import dedent
from datetime import datetime, timedelta

# %% ../../nbs/00_core.ipynb 5
load_dotenv()
apiKey = os.environ["API_KEY_MONDAY"]
apiUrl = "https://api.monday.com/v2"
headers = {"Authorization": f"Bearer {apiKey}", "API-Version": "2023-04"}

# %% ../../nbs/00_core.ipynb 14
def query_sprint_tasks(
    date: str
) -> str:
    return dedent(f"""
    query {{
        boards(ids: 757790388) {{
            items_page(
                query_params: {{
                    rules: [
                        {{
                        column_id: "status_stories",
                        compare_value: [16, 0, 6, 7], #  ["To Do", "Working on it", "Wacht op Antwoord", "Wacht op review"],
                        operator: any_of
                    }}, {{
                        column_id: "date7",
                        compare_value: ["EXACT", "{date}"],
                        operator: lower_than_or_equal
                    }}],
                    operator: and
                    groups: {{
                        rules: [
                            {{ column_id: "person",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }},
                            {{ column_id: "people",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }}
                        ],
                        operator: or
                        }}
                    }},
            ) {{
                cursor
                items {{
                    id
                    name
                    column_values(ids: ["person", "people", "status_stories", "numbers5", "date7", "story_syntax"]) {{
                    id
                    text
                    value
                    }}
                }}
            }}
        }}
    }}
    """).strip()

# %% ../../nbs/00_core.ipynb 15
def query_sprint_tasks(
    date: str
) -> str:
    return dedent(f"""
    query {{
        boards(ids: 757790388) {{
            items_page(
                query_params: {{
                    rules: [
                        {{
                        column_id: "date7",
                        compare_value: ["EXACT", "{date}"],
                        operator: lower_than_or_equal
                    }}],
                    operator: and
                    groups: {{
                        rules: [
                            {{ column_id: "person",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }},
                            {{ column_id: "people",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }}
                        ],
                        operator: or
                        }}
                    }},
            ) {{
                cursor
                items {{
                    id
                    name
                    column_values(ids: ["person", "people", "status_stories", "numbers5", "date7", "story_syntax"]) {{
                    id
                    text
                    value
                    }}
                }}
            }}
        }}
    }}
    """).strip()

# %% ../../nbs/00_core.ipynb 17
query_board_columns = dedent("""
    query {
        boards(
            ids: [757790388]
        ) {
            columns {
                id
                title
                type
            }
        }
    }""").strip()

# %% ../../nbs/00_core.ipynb 19
def get_data(
    query: str,  # GraphQL query
    api_url: str = apiUrl,  # Monday.com API url
    headers: dict = headers,  # Monday.com API headers
) -> dict:  # response from Monday.com API
    data = {"query": query}
    return requests.post(url=api_url, json=data, headers=headers)

# %% ../../nbs/00_core.ipynb 22
def get_start_date(date_str: str) -> str:
    """Get the start date of a task"""
    date_obj = datetime.strptime(date_str, "%Y-%m-%d")
    new_date_obj = date_obj - timedelta(weeks=3) + timedelta(days=1)
    return new_date_obj.strftime("%Y-%m-%d")

# %% ../../nbs/00_core.ipynb 25
def get_items(
    response: requests.models.Response,  # response from Monday.com API
    skip_keys: list = ["data", "items_page_by_column_values", "items"],  # list of key values in the response to skip
) -> list:  # list of items
    return [item for item in response.json().values() if not any(key in item for key in skip_keys)]

# %% ../../nbs/00_core.ipynb 26
def item_to_markdown(
    item: str,  # json formatted string response from Monday.com API
    startdate: str, # start date of the sprint in YYYY-MM-DD format
) -> str:  # Task formatted as Markdown for Obsidian
    """Convert Monday.com item to Markdown task format"""
    # Extract the basic fields
    name = item["name"]

    # Extract role: reviewer or trekker
    
    for col in item["column_values"]:
        if col["id"] == "people" and col["text"] == "Jelle de Jong":
            role = " 🤝reviewer"
            break # break after finding the role
        elif col["id"] == "person" and col["text"] == "Jelle de Jong":
            role = "" 
            break # break after finding the role
        
    # Extract values from column_values
    for col in item["column_values"]:
        if col["id"] == "numbers5":
            try:
                duration = int(col["text"]) * 120
            except ValueError:
                duration = 0
        elif col["id"] == "date7":
            duedate = col["text"]

    # Build the markdown string
    markdown = f"\n- [ ] #sprint {name}{role}"

    # Add duration if present
    if duration > 0:
        markdown += f" [{duration}m]"

    # Add priority emoji
    markdown += " ⏫"  # Priority marker
    # Add created date
    markdown += f" ➕ {startdate}"
    # Add due date if present
    if duedate:
        markdown += f" 📅 {duedate}"

    return markdown

# %% ../../nbs/00_core.ipynb 27
def create_md_tasklist(
    sprint_end_date: str, # end date of the sprint in YYYY-MM-DD format
) -> str:
    """Create a Markdown tasklist for a sprint"""
    q = query_sprint_tasks(sprint_end_date)
    r = get_data(q)
    sprint_start_date = get_start_date(sprint_end_date)
    md = f"# Sprint {sprint_start_date} - {sprint_end_date}\n"
    for item in r.json()["data"]["boards"][0]["items_page"]["items"]:
        md += item_to_markdown(item, sprint_start_date)
    return md
