"""Functions to make the use of Monday.com even easier for Jelle."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['apiKey', 'apiUrl', 'headers', 'query_board_columns', 'q', 'r', 'query_sprint_tasks', 'get_data', 'get_items',
           'item_to_markdown']

# %% ../../nbs/00_core.ipynb 3
import requests
import json
import os
from dotenv import load_dotenv
from textwrap import dedent

# %% ../../nbs/00_core.ipynb 5
load_dotenv()
apiKey = os.environ["API_KEY_MONDAY"]
apiUrl = "https://api.monday.com/v2"
headers = {"Authorization": f"Bearer {apiKey}", "API-Version": "2023-04"}

# %% ../../nbs/00_core.ipynb 14
def query_sprint_tasks(
    date: str
) -> str:
    return dedent(f"""
    query {{
        boards(ids: 757790388) {{
            items_page(
                query_params: {{
                    rules: [
                        {{
                        column_id: "status_stories",
                        compare_value: [16, 0, 6, 7], #  ["To Do", "Working on it", "Wacht op Antwoord", "Wacht op review"],
                        operator: any_of
                    }}, {{
                        column_id: "date7",
                        compare_value: ["EXACT", "{date}"],
                        operator: lower_than_or_equal
                    }}],
                    operator: and
                    groups: {{
                        rules: [
                            {{ column_id: "person",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }},
                            {{ column_id: "people",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }}
                        ],
                        operator: or
                        }}
                    }},
            ) {{
                cursor
                items {{
                    id
                    name
                    column_values(ids: ["person", "people", "status_stories", "numbers5", "date7", "story_syntax"]) {{
                    id
                    text
                    value
                    }}
                }}
            }}
        }}
    }}
    """).strip()

# %% ../../nbs/00_core.ipynb 15
def query_sprint_tasks(
    date: str
) -> str:
    return dedent(f"""
    query {{
        boards(ids: 757790388) {{
            items_page(
                query_params: {{
                    rules: [
                        {{
                        column_id: "date7",
                        compare_value: ["EXACT", "{date}"],
                        operator: lower_than_or_equal
                    }}],
                    operator: and
                    groups: {{
                        rules: [
                            {{ column_id: "person",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }},
                            {{ column_id: "people",
                            compare_value: ["assigned_to_me"],
                            operator: any_of
                            }}
                        ],
                        operator: or
                        }}
                    }},
            ) {{
                cursor
                items {{
                    id
                    name
                    column_values(ids: ["person", "people", "status_stories", "numbers5", "date7", "story_syntax"]) {{
                    id
                    text
                    value
                    }}
                }}
            }}
        }}
    }}
    """).strip()

# %% ../../nbs/00_core.ipynb 17
query_board_columns = dedent("""
    query {
        boards(
            ids: [757790388]
        ) {
            columns {
                id
                title
                type
            }
        }
    }""").strip()

# %% ../../nbs/00_core.ipynb 19
def get_data(
    query: str,  # GraphQL query
    api_url: str = apiUrl,  # Monday.com API url
    headers: dict = headers,  # Monday.com API headers
) -> dict:  # response from Monday.com API
    data = {"query": query}
    return requests.post(url=apiUrl, json=data, headers=headers)

# %% ../../nbs/00_core.ipynb 21
q = query_sprint_tasks("2025-05-14")
r = get_data(q)

r.json()

# %% ../../nbs/00_core.ipynb 24
def get_items(
    response: requests.models.Response,  # response from Monday.com API
    skip_keys: list = ["data", "items_page_by_column_values", "items"],  # list of key values in the response to skip
) -> list:  # list of items
    return [item for item in response.json().values() if not any(key in item for key in skip_keys)]

# %% ../../nbs/00_core.ipynb 25
def item_to_markdown(
    item: str,  # json formatted string response from Monday.com API
) -> str:  # Task formatted as Markdown for Obsidian
    """Convert Monday.com item to Markdown task format"""
    # Extract the basic fields
    name = item["name"]

    # Extract role: reviewer or trekker
    
    for col in item["column_values"]:
        if col["id"] == "people" and col["text"] == "Jelle de Jong":
            role = " 🤝reviewer"
            break # break after finding the role
        elif col["id"] == "person" and col["text"] == "Jelle de Jong":
            role = "" 
            break # break after finding the role
        
    # Extract values from column_values
    for col in item["column_values"]:
        if col["id"] == "numbers5":
            try:
                duration = int(col["text"]) * 120
            except ValueError:
                duration = 0
        elif col["id"] == "date7":
            date = col["text"]

    # Build the markdown string
    markdown = f"- [ ] {name}{role}"

    # Add duration if present
    if duration > 0:
        markdown += f" [{duration}m]"

    # Add priority emoji and date if present
    markdown += " ⏫"  # Priority marker
    if date:
        markdown += f" 📅 {date}"

    return markdown

# %% ../../nbs/00_core.ipynb 26
for item in r.json()["data"]["boards"][0]["items_page"]["items"]:
    print(item_to_markdown(item))
