# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mondaycom',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/mondaycom',
                'lib_path': 'mondaycom'},
  'syms': {'mondaycom.core': {'mondaycom.core.foo': ('core.html#foo', 'mondaycom/core.py')}}}
